---
- name: Install GO
  apt:
    name: "golang"
    state: "latest"

- name: Creates directory
  file:
    path: ~/Downloads/
    state: directory


- name: ls echo
  shell: " ls -la "


- name: Delete the file, if it does exist already
  file:
    path: /usr/local/bin/openvpn_exporter
    state: absent
  ignore_errors: yes



- name: Download openvpn node exporter
  get_url:
    url: "https://github.com/kumina/openvpn_exporter/archive/refs/tags/v0.3.0.tar.gz"
    dest: "~/Downloads/"

- name: Extract archive openvpn node exporter
  command: "tar -xzvf openvpn_exporter-0.3.0.tar.gz"
  args:
    chdir: "~/Downloads"

- name: Copy main.go file to folder
  copy:
    src: "main.go"
    dest: "~/Downloads/openvpn_exporter-0.3.0"

- name: Build the exporter
  shell: "go build -o openvpn_exporter main.go"
  args:
    chdir: "~/Downloads/openvpn_exporter-0.3.0" 

- name: copy shell
  shell: "cp ~/Downloads/openvpn_exporter-0.3.0/openvpn_exporter /usr/local/bin/"

- name: install service
  copy:
    src: openvpn_exporter.service
    dest: /etc/systemd/system
    owner: root
    group: root
    mode: 0755
  notify: reload_daemon_and_restart_openvpn_exporter
